version: "3.7"

services:
  web:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  client:
    build:
      context: ./vue/prueba
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - web
